imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
            channels: [!event, !doctrine] #event,#doctrineチャネルを除外
            formatter: my_formatter # main ハンドラで使うフォーマッタを指定
        console:
            type:   console
            bubble: false
        doctrine:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%_doctrine.log"
            channels: doctrine
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        firephp:
            type:   firephp
            level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

# フォーマッタ設定を追加
services:
    my_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            # フォーマットを定義
            ##- "[%%datetime%%] %%channel%%.%%level_name%%: %%message%%\n"
            - "[%%datetime%%] %%channel%%.%%level_name%%: %%context%% %%extra%%: %%message%%\n"

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com
