kanahei _admin:
    resource: "@KanaheiAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

kanahei_auth:
    resource: "@KanaheiAuthBundle/Resources/config/routing.yml"
    prefix:   /top/auth

kanahei_game:
    resource: "@KanaheiGameBundle/Resources/config/routing.yml"
    prefix:   /

