<?php

namespace Kanahei\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayHistoryRepository extends EntityRepository
{
	public function getSuspended($userId)
	{ 
	return $this->getEntityManager()  
            ->createQuery('SELECT h FROM KanaheiGameBundle:PlayHistory h WHERE h.suspendTime is not null and h.user =:id ORDER BY h.id ASC')->setParameter('id', $userId)
            ->getResult();  
    }
    public function getNotCleared($userId)
	{
	return $this->getEntityManager()  
            ->createQuery('SELECT h FROM KanaheiGameBundle:PlayHistory h WHERE h.clearTime is null and h.user =:id ORDER BY h.id ASC')->setParameter('id', $userId)
            ->getResult();  
    }
}
