<?php

namespace Kanahei\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
	public function questionHistories()  
    {  
        return $this->getEntityManager()  
            ->createQuery('SELECT q, p FROM KanaheiGameBundle:Question q LEFT JOIN q.playHistories p')
            ->getResult();
    }
}