<?php

namespace Kanahei\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RankingPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingPointRepository extends EntityRepository
{
}
