<?php

namespace Kanahei\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findByAuId($auId)  
    {  
        return $this->getEntityManager()  
            ->createQuery('SELECT u FROM KanaheiGameBundle:User u ORDER BY u.auId ASC')  
            ->getResult();  
    }  
}
