<?php

namespace Machigai\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemCategoryRepository extends EntityRepository
{
}
