parameters:
#    machigai_auth.example.class: Machigai\AuthBundle\Example

services:
#    machigai_auth.example:
#        class: %machigai_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
