Top:
    path: /top
    defaults: { _controller: MachigaiGameBundle:Default:index }

Logout:
    path: /logout
    defaults: { _controller: MachigaiGameBundle:Default:logout }

Error:
    path: /error
    defaults: { _controller: MachigaiGameBundle:Default:error }
    requirements: 
        _method: GET

Help:
    pattern: /help/
    defaults: { _controller: MachigaiGameBundle:Help:index }
    requirements: 
        _method: GET

HelpHowtoplay:
    pattern: /help/howtoplay
    defaults: { _controller: MachigaiGameBundle:Help:howtoplay }
    requirements: 
        _method: GET

HelpTerms:
    pattern: /help/terms
    defaults: { _controller: MachigaiGameBundle:Help:terms }
    requirements: 
        _method: GET

HelpInquiryForm:
    pattern: /help/inquiry/form
    defaults: { _controller: MachigaiGameBundle:Help:form }

HelpInquiryFormDo:
    pattern: /help/inquiry/form/do
    defaults: { _controller: MachigaiGameBundle:Help:inquiryFormDo }

HelpInquiryFormComplete:
    pattern: /help/inquiry/form/complete
    defaults: { _controller: MachigaiGameBundle:Help:inquiryFormComplete }

HelpInquiry:
    pattern: /help/inquiry
    defaults: { _controller: MachigaiGameBundle:Help:inquiry }

SettingNicknameregister:
    pattern: /setting/nickname
    defaults: { _controller: MachigaiGameBundle:Setting:nicknameRegister }
    requirements: 
        _method: POST

SettingNickname:
    pattern: /setting/nickname
    defaults: { _controller: MachigaiGameBundle:Setting:nickname }
    requirements: 
        _method: GET

Setting:
    pattern: /setting/
    defaults: { _controller: MachigaiGameBundle:Setting:index }
    requirements: 
        _method: GET

JsonUpload:
    pattern:  /game/uploadData
    defaults: { _controller: MachigaiGameBundle:Game:uploadData }
    requirements:
        _method: POST

SettingComplete:
    pattern: /setting/complete
    defaults: { _controller: MachigaiGameBundle:Setting:complete }

Shop:
    pattern: /shop/
    defaults: { _controller: MachigaiGameBundle:Shop:index }

ShopSort:
    pattern: /shop/{field}/
    defaults: { _controller: MachigaiGameBundle:Shop:indexSort }

ShopWallpaper:
    pattern: /shop/wallpaper/
    defaults: { _controller: MachigaiGameBundle:Shop:wallpaper }

ShopStamp:
    pattern: /shop/stamp/
    defaults: { _controller: MachigaiGameBundle:Shop:stamp }

ShopDownload:
    pattern: /shop/download/{id}
    defaults: { _controller: MachigaiGameBundle:Shop:download }

ShopError:
    pattern: /shop/error/{id}
    defaults: { _controller: MachigaiGameBundle:Shop:error }

confirm:
    pattern: /shop/confirm/{id}
    defaults: { _controller: MachigaiGameBundle:Shop:confirm }

downloadExecute:
    pattern: /shop/downloadExecute/{id}
    defaults: { _controller: MachigaiGameBundle:Shop:downloadExecute }

Ranking:
    pattern: /ranking/
    defaults: { _controller: MachigaiGameBundle:Ranking:index }

GameSelect:
    pattern: /game/select
    defaults: { _controller: MachigaiGameBundle:Game:select }

SortQuestion:
    pattern: /game/select/{sort}
    defaults: { _controller: MachigaiGameBundle:Game:sortQuestions }

GamePlay:
    pattern: /game/play/{id}
    defaults: { _controller: MachigaiGameBundle:Game:play }

GameGetPlayHistory:
    pattern: /game/history
    defaults: { _controller: MachigaiGameBundle:Game:getPlayHistory}

GameGetData:
    pattern: /game/data/
    defaults: { _controller: MachigaiGameBundle:Game:download }

GameDownload:
    pattern: /game/download/{level}/{qcode}/{type}
    defaults: { _controller: MachigaiGameBundle:Game:download }
GameFinish:
    pattern: /game/finish
    defaults: { _controller: MachigaiGameBundle:Game:finish }

GameClear:
    pattern: /game/clear
    defaults: { _controller: MachigaiGameBundle:Game:clear }

GameFail:
    pattern: /game/fail
    defaults: { _controller: MachigaiGameBundle:Game:fail }

Register:
    pattern: /register/
    defaults: { _controller: MachigaiGameBundle:Register:index }

Login:
    pattern: /register/login
    defaults: { _controller: MachigaiGameBundle:Register:login }

RegisterConfirm:
    pattern: /register/confirm/
    defaults: { _controller: MachigaiGameBundle:Register:confirm }

RegisterLogin:
    pattern: /register/login
    defaults: { _controller: MachigaiGameBundle:Register:login }

complete:
    pattern: /register/complete/
    defaults: { _controller: MachigaiGameBundle:Register:complete }

SyncUser:
    pattern: /sync/user
    defaults: { _controller: MachigaiGameBundle:Android:user }
    requirements:
        _method: GET
SyncNotice:
    pattern: /sync/notices
    defaults: { _controller: MachigaiGameBundle:Android:notices }
    requirements:
        _method: GET
SyncGame:
    pattern: /sync/game/
    defaults: { _controller: MachigaiGameBundle:Android:game }
    requirements: 
        _method: GET
SyncGameData:
    pattern: /sync/game/{id}/{fileName}
    defaults: { _controller: MachigaiGameBundle:Android:gameData }
    requirements: 
        _method: GET
