machigai_game_homepage:
    path: /
    defaults: { _controller: MachigaiGameBundle:Default:index }

index:
    pattern: /help/
    defaults: { _controller: MachigaiGameBundle:Help:index }

howtoplay:
    pattern: /help/howtoplay
    defaults: { _controller: MachigaiGameBundle:Help:howtoplay }

terms:
    pattern: /help/terms
    defaults: { _controller: MachigaiGameBundle:Help:terms }

inquiry:
    pattern: /help/inquiry
    defaults: { _controller: MachigaiGameBundle:Help:inquiry }

index:
    pattern: /setting/
    defaults: { _controller: MachigaiGameBundle:Setting:index }

username:
    pattern: /setting/username
    defaults: { _controller: MachigaiGameBundle:Setting:username }

complete:
    pattern: /setting/complete
    defaults: { _controller: MachigaiGameBundle:Setting:complete }
